import type { LoadedTemplate, MergeTemplateInput } from './template-types';

export interface MergeTemplatesOptions {
    generatedBy?: string;
    includeHeader?: boolean;
    includeSectionHeaders?: boolean;
    sourceUrl?: string;
}

function normalizeRuleLine(line: string): string {
    return line.trim();
}

function collapseBlankLines(lines: string[]): string[] {
    const result: string[] = [];
    let previousBlank = false;

    for (const line of lines) {
        const isBlank = line.trim() === '';

        if (isBlank) {
            if (!previousBlank) {
                result.push('');
            }
            previousBlank = true;
            continue;
        }

        previousBlank = false;
        result.push(line);
    }

    return result;
}

export function mergeTemplateContents(
    templates: MergeTemplateInput[],
    options: MergeTemplatesOptions = {},
): string {
    const includeHeader = options.includeHeader ?? true;
    const includeSectionHeaders = options.includeSectionHeaders ?? true;
    const generatedBy = options.generatedBy ?? 'gitignore.sh';

    const seenRules = new Set<string>();
    const output: string[] = [];

    if (includeHeader) {
        output.push(`# Generated by ${generatedBy}`);
        if (options.sourceUrl) {
            output.push(`# ${options.sourceUrl}`);
        }
        output.push(`# Templates: ${templates.map((template) => template.id).join(', ') || 'none'}`);
        output.push('');
    }

    templates.forEach((template, index) => {
        if (includeSectionHeaders) {
            output.push(`### ${template.name} ###`);
        }

        const lines = template.content.replace(/\r\n/g, '\n').split('\n');

        for (const line of lines) {
            const trimmed = line.trim();

            if (!trimmed) {
                output.push('');
                continue;
            }

            if (trimmed.startsWith('#')) {
                output.push(line);
                continue;
            }

            const normalizedRule = normalizeRuleLine(line);
            if (seenRules.has(normalizedRule)) {
                continue;
            }

            seenRules.add(normalizedRule);
            output.push(line);
        }

        if (index < templates.length - 1) {
            output.push('');
        }
    });

    return `${collapseBlankLines(output).join('\n').trimEnd()}\n`;
}

export function mergeLoadedTemplates(
    templates: LoadedTemplate[],
    options: MergeTemplatesOptions = {},
): string {
    return mergeTemplateContents(templates, options);
}